server.ssl.enabled: false
server.port: 8080

cas.authn.accept.users: inwebo1::inwebo1,inwebom::inwebom,inwebop::inwebop,inwebov::inwebov

cas.tgc.secure: false
cas.tgc.same-site-policy: Lax

cas.tgc.crypto.enabled: false
cas.webflow.crypto.enabled: false

cas.server.name: http://localhost:8080
cas.server.prefix: http://localhost:8080/cas
cas.host.name: castest

cas.authn.oauth.code.timeToKillInSeconds: 30000
cas.authn.oauth.code.numberOfUses: 10000

cas.ticket.st.numberOfUses: 1000
cas.ticket.st.timeToKillInSeconds: 10000

cas.serviceRegistry.json.location: classpath:/services

cas.authn.mfa.triggers.global.global-provider-id: mfa-inwebo

cas.authn.mfa.inwebo.client-certificate.certificate.location: classpath:castest.p12
cas.authn.mfa.inwebo.client-certificate.passphrase: itsmycert
cas.authn.mfa.inwebo.site-alias: c429850d6433996239aac6570d6edb48
cas.authn.mfa.inwebo.service-id: 7046
#cas.authn.mfa.inwebo.push-enabled: false
cas.authn.mfa.inwebo.browser-authenticator: VIRTUAL_AUTHENTICATOR
